// This file is automatically generated, do not edit it.
export const fdTabs: string;
export const tabsHead: string;
export const headItem: string;
export const selected: string;
export const headIndicator: string;
export const indicatorInner: string;
export const tabsBody: string;
export const bodyItem: string;
